app = "corgi-recommender"
primary_region = "sjc"  # San Jose, California

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  FLASK_ENV = "production"
  DEBUG = "false"
  LOG_LEVEL = "INFO"
  WORKERS = "2"
  THREADS = "4"
  WORKER_CLASS = "gthread"
  RANKING_INCLUDE_SYNTHETIC = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[metrics]
  port = 8080
  path = "/metrics"

[[vm]]
  memory = "512MB"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "bluegreen"  # Zero downtime deployments

[healthcheck]
  path = "/health"
  port = 8080
  interval = "15s"
  timeout = "5s"
  grace_period = "10s"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[mounts]
  source = "corgi_recommender_data"
  destination = "/data"