services:
  # Web service - API endpoints
  - type: web
    name: corgi-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh ./start.sh
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: 2
      - key: THREADS
        value: 4
      - key: WORKER_CLASS
        value: gthread
      - key: RANKING_INCLUDE_SYNTHETIC
        value: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*" # In production, specify your actual frontend domains
      - key: POSTGRES_HOST
        fromDatabase:
          name: corgi-recommender-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: corgi-recommender-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: corgi-recommender-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: corgi-recommender-db
          property: password
      - key: USER_HASH_SALT
        generateValue: true

# PostgreSQL Database
databases:
  - name: corgi-recommender-db
    plan: starter