global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'corgi-recommender'
    static_configs:
      - targets: ['host.docker.internal:9100']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:

  # Test Suite Metrics
  - job_name: 'test-metrics'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

      - targets: ['localhost:9090']