name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
          # Install any other dependencies your docs might need
          pip install mike
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Build MkDocs site
        run: mkdocs build
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2